### ISSUE TITLE
Crash when launching cemu

### ISSUE THREAD

**Issue by SwitchTre** [etra0/botw-freecam#15] opened 2021-03-12 17:39 UTC
botw-freecam.exe crashes as soon as Cemu is opened. Says "waiting for the process to start" then says "game found dll address 230000 error the operation completed sucessfully" for a split second then crashes.

Win 7
Intel 4790k
16gb ddr3
Cemu 1.22.7

**Comment by etra0** [comment] 2021-03-12 18:13
after it says that do you get a new terminal window? or do you see nothing?

**Comment by SwitchTre** [comment] 2021-03-12 21:43
No, nothing comes up after. Nothing in task manager

**Comment by SwitchTre** [comment] 2021-03-12 21:52
Both Cemu and freecam.exe are ran as admin. I'm going to download Cemu 1.22.2 and test to see if that's the issue

**Comment by SwitchTre** [comment] 2021-03-14 20:12
Cemu 1.22.2 gave me the same results. Any ideas?

**Comment by etra0** [comment] 2021-03-14 21:15
What's your system language? do you have either Cemu or the tool on a non-ascii folder?

**Comment by SwitchTre** [comment] 2021-03-15 01:25
Win 7 x64/x86￼

**Comment by etra0** [comment] 2021-03-15 20:28
hmm, it could be a utf-8 issue, I fixed one a bit ago, try redownloading 0.2.2 again just in case and tell me how it goes.

**Comment by SwitchTre** [comment] 2021-03-16 14:10
Ok redownloaded 0.2.2 and Tested 0.2.3, same result. I believe it's my cpu since my 4970k was released in 2014 I'm guessing there's support issues here

**Comment by SwitchTre** [comment] 2021-03-16 16:19
Regardless, You have done some great work here with this tool! Emu community is boss. Maybe, once I upgrade my internet we can raid some folks in Rust. Take care.

**Comment by etra0** [comment] 2021-03-16 21:29
> 
> 
> Ok redownloaded 0.2.2 and Tested 0.2.3, same result. I believe it's my cpu since my 4970k was released in 2014 I'm guessing there's support issues here

Did you received the error message? if you still have an instant crash the issue is not related with your CPU age. I think I've read somewhere that the 4970k supports the `movbe` instruction so it could still be another issue.

**Comment by DigitalFrontiers** [comment] 2021-03-16 22:00
Just to chime in for what it's worth, my pc has a 4970k (32gb ram, ssd, 1080ti, win 8.1) and everything works with no issues.

**Comment by DigitalFrontiers** [comment] 2021-03-16 22:02
I'm using Cemu 1.22.3b btw.

**Comment by SwitchTre** [comment] 2021-03-16 22:35
Okay. I'm still "error operation completed successfully" and crash. This is interesting

**Comment by SwitchTre** [comment] 2021-03-16 22:47
Maybe this is the issue. My game dump may be broken,looks like the update data was merged with the base game

**Comment by SwitchTre** [comment] 2021-04-07 21:52
Also running 1080 ti Intel system Cemu 1.22.9d cemuhook 0.5.7.3 Progress report: performed clean install of botw, update v208, and dlc. Getting the same crash with message "Waiting for the process to start/ Game found/ DDL address 2d10000/ handle 0x20/ Error: The operation completed successfully." Nothing in task manager once cemu opens. Any other suggestions?

**Comment by etra0** [comment] 2021-04-07 22:29
> Also running 1080 ti Intel system Cemu 1.22.9d cemuhook 0.5.7.3 Progress report: performed clean install of botw, update v208, and dlc. Getting the same crash with message "Waiting for the process to start/ Game found/ DDL address 2d10000/ handle 0x20/ Error: The operation completed successfully." Nothing in task manager once cemu opens. Any other suggestions?

are you running the v0.2.4 of the freecam?

**Comment by SwitchTre** [comment] 2021-04-08 12:56
@etra0 yes, tested with latest version

**Comment by etra0** [comment] 2021-04-08 21:26
Hmm, the only thing I can think of for testing is to put both the tool and cemu in a root directory (something like C:\Cemu and C:\freecam for example) to test if it's an username issue or something, but really I'm out of ideas for testing your case.

**Comment by SwitchTre** [comment] 2021-04-09 23:11
Alright I'll give that a try, I appreciate the help thank you

**Closed** 2021-08-18 22:53 UTC
Labels: question
