### ISSUE TITLE
[Feature Request] Time Freeze

### ISSUE THREAD

**Issue by mattsxp** [etra0/botw-freecam#31] opened 2021-09-29 07:47 UTC
First of all, thank you for this! I'm incredibly grateful you made this, and I can't tell you how much I appreciate it.

If I might be able to make a request, do you think it would be possible to incorporate a 'pause time' hotkey,[ similar to this mod someone created on top of your mod through Cheat Engine?](https://gamebanana.com/tools/7052) As someone very surface-level with mods and not familiar at all with Cheat Engine, I'd rather not use that tool. This functionality seems like something that could possibly be incorporated in your mod from the start. By all means, correct me if I'm wrong. 

Please let me know! All the best.

**Comment by etra0** [comment] 2021-11-02 01:22
Duplicate of https://github.com/etra0/botw-freecam/issues/8

**Closed by etra0** 2021-11-02 01:22 UTC
